chore: fix

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -43,57 +43,57 @@ jobs:
     steps:
       - uses: actions/checkout@v4
 
-    - name: Install pnpm
-      uses: pnpm/action-setup@v4
+      - name: Install pnpm
+        uses: pnpm/action-setup@v4
 
-    - name: Set node version to ${{ matrix.node_version }}
-      uses: actions/setup-node@v4
-      with:
-        node-version: ${{ matrix.node_version }}
+      - name: Set node version to ${{ matrix.node_version }}
+        uses: actions/setup-node@v4
+        with:
+          node-version: ${{ matrix.node_version }}
 
-    - name: Resolve package versions
-      id: resolve-package-versions
-      shell: bash
-      run: >
-        echo "$(
-          node -e "
-            const fs = require('fs');
-            const lockfile = fs.readFileSync('./pnpm-lock.yaml', 'utf8');
-            const pattern = (name) => new RegExp(name + ':\\\s+specifier: [\\\s\\\w\\\.^]+version: (\\\d+\\\.\\\d+\\\.\\\d+)');
-            const playwrightVersion = lockfile.match(pattern('playwright'))[1];
-            console.log('PLAYWRIGHT_VERSION=' + playwrightVersion);
-          "
-        )" >> $GITHUB_OUTPUT
+      - name: Resolve package versions
+        id: resolve-package-versions
+        shell: bash
+        run: >
+          echo "$(
+            node -e "
+              const fs = require('fs');
+              const lockfile = fs.readFileSync('./pnpm-lock.yaml', 'utf8');
+              const pattern = (name) => new RegExp(name + ':\\\s+specifier: [\\\s\\\w\\\.^]+version: (\\\d+\\\.\\\d+\\\.\\\d+)');
+              const playwrightVersion = lockfile.match(pattern('playwright'))[1];
+              console.log('PLAYWRIGHT_VERSION=' + playwrightVersion);
+            "
+          )" >> $GITHUB_OUTPUT
 
-    - name: Print versions
-      shell: bash
-      run: echo "${{ toJson(steps.resolve-package-versions.outputs) }}"
+      - name: Print versions
+        shell: bash
+        run: echo "${{ toJson(steps.resolve-package-versions.outputs) }}"
 
-    - name: Check resolved package versions
-      shell: bash
-      if: |
-        contains(fromJSON('[null, "", "undefined"]'), steps.resolve-package-versions.outputs.PLAYWRIGHT_VERSION)
-      run: echo "Failed to resolve package versions. See log above." && exit 1
+      - name: Check resolved package versions
+        shell: bash
+        if: |
+          contains(fromJSON('[null, "", "undefined"]'), steps.resolve-package-versions.outputs.PLAYWRIGHT_VERSION)
+        run: echo "Failed to resolve package versions. See log above." && exit 1
 
-    - name: Cache Playwright v${{ steps.resolve-package-versions.outputs.PLAYWRIGHT_VERSION }}
-      uses: actions/cache@v4
-      id: playwright-cache
-      with:
-        path: ${{ env.PLAYWRIGHT_BROWSERS_PATH }}
-        key: ${{ runner.os }}-playwright-${{ steps.resolve-package-versions.outputs.PLAYWRIGHT_VERSION }}
-        restore-keys: |
-          ${{ runner.os }}-playwright-
+      - name: Cache Playwright v${{ steps.resolve-package-versions.outputs.PLAYWRIGHT_VERSION }}
+        uses: actions/cache@v4
+        id: playwright-cache
+        with:
+          path: ${{ env.PLAYWRIGHT_BROWSERS_PATH }}
+          key: ${{ runner.os }}-playwright-${{ steps.resolve-package-versions.outputs.PLAYWRIGHT_VERSION }}
+          restore-keys: |
+            ${{ runner.os }}-playwright-
 
-      - uses: browser-actions/setup-chrome@v1
+        - uses: browser-actions/setup-chrome@v1
 
-      - name: Install
-        run: pnpm i
+        - name: Install
+          run: pnpm i
 
-      - name: Install Playwright Dependencies
-        run: pnpm exec playwright install chromium --with-deps
+        - name: Install Playwright Dependencies
+          run: pnpm exec playwright install chromium --with-deps
 
-      - name: Build
-        run: pnpm run build
+        - name: Build
+          run: pnpm run build
 
-      - name: Test
-        run: pnpm run test
+        - name: Test
+          run: pnpm run test
